### ISSUE TITLE
conflict در نام کلاس

### ISSUE THREAD

**Issue by mohammadrafigh** [mohamad-amin/PersianMaterialDateTimePicker#17]
درود بر شما،

ممنون از این که [این](https://github.com/wdullaer/MaterialDateTimePicker) کتاب خونه رو فارسی سازی کردید.
اما من تو یه پروژه نیاز به استفاده از هر دوی این‌ها دارم، یعنی هم خورشیدی هم میلادی و ظاهرا هر دوی این‌ها رو کنار هم نمیشه تو یه پروژه با gradle داشت و نهایتا موقع run کردن به exception و conflict بر می خوره بین اسم کلاس‌های داخل لایبرری شما.

ممنون

**Comment by mohamad-amin** [comment]
سلام
بله درست میگید بنده این حالتو در نظر نگرفتم
ولی خب مگه پکیج این دوتا کتابخونه متفاوت نیست؟
اگر اینطور هست نباید مشکلی پیش بیاد
خط اخر نوشته‌های شما هم برای بنده خیلی قابل فهم نبود
اگر ممکنه واضح تر بگید
با تشکر

**Comment by mohammadrafigh** [comment]
ozr mikham az in ke dir javab dadam, latin minevisam ke RTL esh be ham nakhore ;)
package bale jodas manam ta'ajobam az hamine ke chera conflict mikhore. jomleye akhare payame bala ham in bood:
"zaheran har doye ina ro kenare ham nemishe too ye project ba gradle dasht va nahayatan mogheye run kardan be exception o conflict beyne class haye library e shoma bar mikhore...

fekr konam be onvane ye workaround e movaghat shayad in kar javab bede ke source ro be onvane module dakhele app bezaramo test konam. amma shayad behtar bashe ye joore dige in moshkel hal beshe shayad masalan shoma betoonid har 2 taghvime khorshidio miladi ro ba ham too ye library gharar bedid va merge request bedid baraye oon yeki library...

baz ham mamnoon az tavajohetoon

**Comment by mohammadrafigh** [comment]
jahate asoon tar shodane kar in exception hastesh:

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.payamgostar.formmaker, PID: 3063
                                                                         java.lang.ClassCastException: com.wdullaer.materialdatetimepicker.date.AccessibleDateAnimator cannot be cast to com.mohamadamin.persianmaterialdatetimepicker.date.AccessibleDateAnimator
                                                                             at com.mohamadamin.persianmaterialdatetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:255)
                                                                             at android.app.Fragment.performCreateView(Fragment.java:2053)
                                                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                             at android.app.BackStackRecord.run(BackStackRecord.java:834)
                                                                             at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
                                                                             at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by mohammadrafigh** [comment]
ye rahe hale sade ine ke dakhele DatePickerDialog va har jaye dige ke cast anjam dadid az class haye khodetoon, cast ha ro ba esme package anjam bedid... ye rahe dige ham ine ke kolan esme tamame class hatoon ro avaz konid.

**Comment by mohammadrafigh** [comment]
man ino halesh kardam, shoma kafie resource haye layout etoon ro esme hamashoon ro avaz konid, ye refactor --> rename konid.
etefaghi ke miofte ine ke vaghti az in library va oon yeki library kenare ham estefade mishe, chon az resource haye xml e ham nam estefade mikonid (be khosoos dar layout), vaghti mikhad layout inflate beshe az R ya resource e shoma ro mikhoone ya baraye library e asli (English), va vaghti mikhad oon view ro cast kone nemitoone in karo anjam bede chon class e view ha too package haye mokhtalefi hastan va mahiate motefavet va version haye motefaveti daran.
dar vaghe class haye javaye shoma doroste va too package haye khodeshoon hastan amma resource haye layout etoon vaghti dar yek R e vahed gharar migiran ba ham be conflict mikhore.
man noskheye english ro module kardam va resource haye oono taghire nam dadam chon project e shoma module nemishod zaheran ye seri az file hatoon dorost config nist. age khodetoon betoonid rename konid va version e jadid bedid kheyli khoob mishe, zemne in ke too noskheye jadide taghvime english emkane taghire rang az dakhele java ham faraham shode (setAccentColor()) oono ham mitoonid merge konid begirid.
